name: Test

on:
  push:

env:
  PACKAGES: |
    /usr/bin/dbus-daemon
    gcc
    git
    meson
    pkgconfig(dbus-1)
    pkgconfig(gio-2.0)
    pkgconfig(gobject-introspection-1.0)
    yggdrasil

jobs:
  test:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:rawhide
    steps:
      - run: dnf install --assumeyes $PACKAGES
      - uses: actions/checkout@v3
      - run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - run: meson setup $GITHUB_WORKSPACE/builddir
      - run: meson compile -C $GITHUB_WORKSPACE/builddir
      - run: meson test -C $GITHUB_WORKSPACE/builddir --verbose
